name: Python Test Project

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Run Tests
        run: python -m unittest auto_tests.py
